"""provider_credentials

Revision ID: 6bac9c19361c
Revises: d2b49e5d76cd
Create Date: 2026-06-08 08:32:06.008624
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6bac9c19361c'
down_revision: Union[str, None] = 'd2b49e5d76cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('data_enc', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_credentials_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_credentials_user_id'))

    op.drop_table('provider_credentials')
    # ### end Alembic commands ###
