"""asset beat_config

Revision ID: a237302a6280
Revises: 0e21f2ec6bba
Create Date: 2026-06-11 09:27:31.833835
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a237302a6280'
down_revision: Union[str, None] = '0e21f2ec6bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beat_config', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('beat_config')

    # ### end Alembic commands ###
