"""asset name column

Revision ID: d53a7dadb3ef
Revises: 6bac9c19361c
Create Date: 2026-06-08 14:35:08.755702
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd53a7dadb3ef'
down_revision: Union[str, None] = '6bac9c19361c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
